/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/s21_memchr.check" instead.
 */

#include <check.h>
#include <stdio.h>

#include <string.h>
#include "../s21_string.h"
START_TEST(test_s21_memchr_normal) {
    void *str = (void*) "Hello world";
    ck_assert_str_eq(s21_memchr(str, 111, 10), memchr(str, 111, 10));
}
END_TEST

START_TEST(test_s21_memchr_no_result) {
    void *str2 = (void*) "Hello world";
    void *str1 = (void*) "Hello world";
    ck_assert_ptr_eq(s21_memchr(str1, 107, 11), memchr(str2, 107, 11));
}
END_TEST

START_TEST(test_s21_memchr_empty_str) {
    void *str1 = (void*) "\0";
    void *str2 = (void*) "\0";
    ck_assert_ptr_eq(s21_memchr(str1, 12, 1), memchr(str2, 12, 1));

#include <string.h>
#include "../s21_string.h"
}
END_TEST

START_TEST(test_s21_memcmp_normal) {
    void *str1 = (void*) "Hello world";
    void *str2 = (void*) "Hello world";
    ck_assert_int_eq(s21_memcmp(str1, str2, 11), memcmp(str1, str2, 11));
}
END_TEST

START_TEST(test_s21_memcmp_not_equal) {
    void *str1 = (void*) "Hello world";
    void *str2 = (void*) "HELLO WORLD";
    ck_assert_int_eq(s21_memcmp(str1, str2, 11), memcmp(str1, str2, 11));
}
END_TEST

START_TEST(test_s21_memcmp_empty_str) {
    void *str1 = (void*) "\0";
    void *str2 = (void*) "\0";
    ck_assert_int_eq(s21_memcmp(str1, str2, 1), memcmp(str1, str2, 1));
#include <string.h>
#include "../s21_string.h"
}
END_TEST

START_TEST(test_s21_memcpy_full) {
    void *template = (void*) "Hello world";
    char buff1[50]; char buff2[50];
    void *str1 = (void*) buff1;
    void *str2 = (void*) buff2;
    memcpy(str1, template, 10);
    s21_memcpy(str2, template, 10);
    ck_assert_int_eq(memcmp(str1, str2, 10), 0);
}
END_TEST

START_TEST(test_s21_memcpy_partial) {
    void *template = (void*) "Text to copy";
    char buff1[50]; char buff2[50];
    void *str1 = (void*) buff1;
    void *str2 = (void*) buff2;
    memcpy(str1, template, 5);
    s21_memcpy(str2, template, 5);
    ck_assert_int_eq(memcmp(str1, str2, 5), 0);
}
END_TEST

START_TEST(test_s21_memcpy_empty) {
    void *template = (void*) "\0";
    char buff1[50]; char buff2[50];
    void *str1 = (void*) buff1;
    void *str2 = (void*) buff2;
    memcpy(str1, template, 1);
    s21_memcpy(str2, template, 1);
    ck_assert_int_eq(memcmp(str1, str2, 1), 0);

}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_s21_memchr_normal);
    tcase_add_test(tc1_1, test_s21_memchr_no_result);
    tcase_add_test(tc1_1, test_s21_memchr_empty_str);
    tcase_add_test(tc1_1, test_s21_memcmp_normal);
    tcase_add_test(tc1_1, test_s21_memcmp_not_equal);
    tcase_add_test(tc1_1, test_s21_memcmp_empty_str);
    tcase_add_test(tc1_1, test_s21_memcpy_full);
    tcase_add_test(tc1_1, test_s21_memcpy_partial);
    tcase_add_test(tc1_1, test_s21_memcpy_empty);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
